#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const sourcePath = join(here, 'AGENTS.md');
const sourceBytes = readFileSync(sourcePath);
const sourceText = sourceBytes.toString('utf8');

function sha256(value) {
  return `sha256:${createHash('sha256').update(value).digest('hex')}`;
}

function canonicalize(text) {
  return text.normalize('NFC').replace(/\r\n/g, '\n');
}

function stripFrontmatter(text) {
  return text.replace(/^---\n[\s\S]*?\n---\n\n?/, '');
}

function renderGeneratedHeader(timestamp) {
  return `Generated by a context sync tool at ${timestamp}. Do not edit manually.\n\n`;
}

const canonicalText = canonicalize(sourceText);
const source = {
  path: 'examples/context-input-evidence/AGENTS.md',
  bytes_hash: sha256(sourceBytes),
  canonical_form: 'otel.context.source.nfc_lf.v1_candidate',
  canonical_hash: sha256(canonicalText),
  canonicalization: ['utf8', 'unicode_nfc', 'crlf_to_lf']
};

const generatedFallbackBody = stripFrontmatter(sourceText);
const generatedFallbackTemplate = 'Generated by a context sync tool at {{generated_at}}. Do not edit manually.\n\n{{body}}';
const clippedRender = sourceText.replaceAll('{{repo_root}}', '/workspace/example-service');
const clippedAtIngestText = clippedRender.slice(0, 120);

const deliveries = [
  {
    tool: 'claude-code',
    loadedBy: 'native-file-discovery',
    deliveryTransform: 'source-as-delivered',
    text: sourceText,
    fullText: sourceText,
    nondeterministic: false,
    dedupeScope: 'session'
  },
  {
    tool: 'codex',
    loadedBy: 'native-agents-md',
    deliveryTransform: 'post-template-expansion',
    text: clippedRender,
    fullText: clippedRender,
    templateHash: sha256(sourceText.replaceAll('{{repo_root}}', '{{repo_root}}')),
    nondeterministic: false,
    dedupeScope: 'session'
  },
  {
    tool: 'cursor',
    loadedBy: 'generated-generic-fallback',
    deliveryTransform: 'frontmatter-stripped-with-generated-header',
    text: `${renderGeneratedHeader('2026-05-20T17:00:00.000Z')}${generatedFallbackBody}`,
    fullText: `${renderGeneratedHeader('2026-05-20T17:00:00.000Z')}${generatedFallbackBody}`,
    templateHash: sha256(generatedFallbackTemplate),
    nondeterministic: true,
    nondeterminismReason: 'generated_header_timestamp',
    dedupeScope: 'session'
  },
  {
    tool: 'cursor',
    loadedBy: 'generated-generic-fallback',
    deliveryTransform: 'same-logical-load-different-generated-header',
    text: `${renderGeneratedHeader('2026-05-20T17:00:01.000Z')}${generatedFallbackBody}`,
    fullText: `${renderGeneratedHeader('2026-05-20T17:00:01.000Z')}${generatedFallbackBody}`,
    templateHash: sha256(generatedFallbackTemplate),
    nondeterministic: true,
    nondeterminismReason: 'generated_header_timestamp',
    dedupeScope: 'session'
  },
  {
    tool: 'small-window-harness',
    loadedBy: 'native-file-discovery',
    deliveryTransform: 'post-template-expansion-clipped-for-window',
    text: clippedRender.slice(0, 180),
    fullText: clippedRender,
    templateHash: sha256(sourceText.replaceAll('{{repo_root}}', '{{repo_root}}')),
    nondeterministic: false,
    truncated: true,
    truncationLimitChars: 180,
    fullRenderStatus: 'available',
    dedupeScope: 'session'
  },
  {
    tool: 'ingest-clipping-harness',
    loadedBy: 'native-file-discovery',
    deliveryTransform: 'clipped-at-ingest-full-render-not-materialized',
    text: clippedAtIngestText,
    fullText: null,
    templateHash: sha256(sourceText.replaceAll('{{repo_root}}', '{{repo_root}}')),
    nondeterministic: false,
    truncated: true,
    truncationLimitChars: 120,
    fullRenderStatus: 'unavailable_not_materialized',
    dedupeScope: 'session'
  }
];

const sessionId = 'demo-session-context-input-evidence';
const now = '2026-05-20T18:00:00.000Z';
const events = deliveries.map((delivery) => {
  const deliveredHash = sha256(delivery.text);
  const fullRenderHash = delivery.fullText == null ? null : sha256(delivery.fullText);
  const fullRenderStatus = delivery.fullRenderStatus ?? 'available';
  const duplicateBasis = delivery.truncated && fullRenderHash ? fullRenderHash : deliveredHash;
  const suppressionPolicy = delivery.nondeterministic
    ? 'keep_distinct_template_hash_is_candidate_only'
    : delivery.truncated && !fullRenderHash
      ? 'keep_distinct_full_render_unknown'
      : 'suppress_equal_dedupe_key_within_scope';

  return {
    trace_id: 'demo-trace-context-input-evidence',
    span_id: sessionId,
    name: 'context.input.loaded',
    time: now,
    attributes: {
      'context.input.kind': 'agent_instructions',
      'context.input.source.path': source.path,
      'context.input.source.bytes_hash': source.bytes_hash,
      'context.input.source.canonical.form': source.canonical_form,
      'context.input.source.canonical.hash': source.canonical_hash,
      'context.input.source.canonicalization': source.canonicalization.join(','),
      'context.input.delivered.hash': deliveredHash,
      'session.id': sessionId,
      'gen_ai.conversation.id': sessionId,
      'context.input.delivered.full_render.hash': fullRenderHash ?? '',
      'context.input.delivered.full_render.status': fullRenderStatus,
      'context.input.delivered.template_hash': delivery.templateHash ?? '',
      'context.input.delivered.transform': delivery.deliveryTransform,
      'context.input.delivered.nondeterministic': String(Boolean(delivery.nondeterministic)),
      'context.input.delivered.nondeterminism_reason': delivery.nondeterminismReason ?? '',
      'context.input.delivered.truncated': String(Boolean(delivery.truncated)),
      'context.input.delivered.truncation_limit_chars': String(delivery.truncationLimitChars ?? ''),
      'context.input.loaded_by': delivery.loadedBy,
      'context.input.activation': 'session_start',
      'context.input.scope': 'repo',
      'context.input.applies_to': delivery.tool,
      'context.input.why_loaded': 'shared invariant guidance',
      'context.input.expected_benefit': 'align agent behavior with repository conventions',
      'context.input.duplicate.dedupe_key': `${delivery.dedupeScope}:${duplicateBasis}`,
      'context.input.duplicate.dedupe_scope': delivery.dedupeScope,
      'context.input.duplicate.suppression_policy': suppressionPolicy,
      'context.input.duplicate.role': 'selected',
      'context.input.duplicate.risk': 'unknown'
    }
  };
});

const outputPath = join(here, 'receipt.ndjson');
writeFileSync(outputPath, `${events.map((event) => JSON.stringify(event)).join('\n')}\n`);

const deliveredHashes = new Set(events.map((event) => event.attributes['context.input.delivered.hash']));
const templateHashes = new Set(events.map((event) => event.attributes['context.input.delivered.template_hash']).filter(Boolean));
const nondeterministicEvents = events.filter((event) => event.attributes['context.input.delivered.nondeterministic'] === 'true');
const truncatedEvents = events.filter((event) => event.attributes['context.input.delivered.truncated'] === 'true');

const summary = {
  schema: 'pluribus.contextInputEvidence.demo.v0',
  eventCount: events.length,
  sourceBytesHash: source.bytes_hash,
  sourceCanonicalForm: source.canonical_form,
  sourceCanonicalHash: source.canonical_hash,
  deliveredHashCount: deliveredHashes.size,
  templateHashCount: templateHashes.size,
  nondeterministicEventCount: nondeterministicEvents.length,
  truncatedEventCount: truncatedEvents.length,
  dedupeScope: 'session',
  sourceBytesIdenticalAcrossTools: true,
  deliveredHashesDiverge: deliveredHashes.size > 1,
  receiptPath: 'examples/context-input-evidence/receipt.ndjson',
  lesson: 'Do not use one content.hash for source identity, canonical comparison, delivered identity, template stability, and truncation-aware dedupe.'
};

console.log(JSON.stringify(summary, null, 2));
