#!/usr/bin/env node
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const sourcePath = join(here, 'AGENTS.md');
const sourceBytes = readFileSync(sourcePath);
const sourceText = sourceBytes.toString('utf8');

function sha256(value) {
  return `sha256:${createHash('sha256').update(value).digest('hex')}`;
}

function canonicalize(text) {
  return text.normalize('NFC').replace(/\r\n/g, '\n');
}

function stripFrontmatter(text) {
  return text.replace(/^---\n[\s\S]*?\n---\n\n?/, '');
}

const canonicalText = canonicalize(sourceText);
const source = {
  path: 'examples/context-input-evidence/AGENTS.md',
  bytes_hash: sha256(sourceBytes),
  canonical_hash: sha256(canonicalText),
  canonicalization: ['utf8', 'unicode_nfc', 'crlf_to_lf']
};

const deliveries = [
  {
    tool: 'claude-code',
    loadedBy: 'native-file-discovery',
    deliveryTransform: 'source-as-delivered',
    text: sourceText
  },
  {
    tool: 'codex',
    loadedBy: 'native-agents-md',
    deliveryTransform: 'post-template-expansion',
    text: sourceText.replaceAll('{{repo_root}}', '/workspace/example-service')
  },
  {
    tool: 'cursor',
    loadedBy: 'generated-generic-fallback',
    deliveryTransform: 'frontmatter-stripped-with-generated-header',
    text: `Generated by a context sync tool. Do not edit manually.\n\n${stripFrontmatter(sourceText)}`
  }
];

const sessionId = 'demo-session-context-input-evidence';
const now = '2026-05-20T17:00:00.000Z';
const events = deliveries.map((delivery) => {
  const deliveredHash = sha256(delivery.text);
  return {
    trace_id: 'demo-trace-context-input-evidence',
    span_id: sessionId,
    name: 'context.input.loaded',
    time: now,
    attributes: {
      'context.input.kind': 'agent_instructions',
      'context.input.source.path': source.path,
      'context.input.source.bytes_hash': source.bytes_hash,
      'context.input.source.canonical_hash': source.canonical_hash,
      'context.input.source.canonicalization': source.canonicalization.join(','),
      'context.input.delivered.hash': deliveredHash,
      'context.input.delivered.transform': delivery.deliveryTransform,
      'context.input.loaded_by': delivery.loadedBy,
      'context.input.activation': 'session_start',
      'context.input.scope': 'repo',
      'context.input.applies_to': delivery.tool,
      'context.input.why_loaded': 'shared invariant guidance',
      'context.input.expected_benefit': 'align agent behavior with repository conventions',
      'context.input.duplicate.dedupe_key': deliveredHash,
      'context.input.duplicate.role': 'selected',
      'context.input.duplicate.risk': 'unknown'
    }
  };
});

const outputPath = join(here, 'receipt.ndjson');
writeFileSync(outputPath, `${events.map((event) => JSON.stringify(event)).join('\n')}\n`);

const deliveredHashes = new Set(events.map((event) => event.attributes['context.input.delivered.hash']));
const summary = {
  schema: 'pluribus.contextInputEvidence.demo.v0',
  sourceBytesHash: source.bytes_hash,
  sourceCanonicalHash: source.canonical_hash,
  deliveredHashCount: deliveredHashes.size,
  sourceBytesIdenticalAcrossTools: true,
  deliveredHashesDiverge: deliveredHashes.size > 1,
  receiptPath: 'examples/context-input-evidence/receipt.ndjson',
  lesson: 'Do not use one content.hash for both source identity and delivered/dedupe identity.'
};

console.log(JSON.stringify(summary, null, 2));
