import test from 'node:test'
import assert from 'node:assert/strict'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawnSync } from 'node:child_process'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const cliPath = path.join(repoRoot, 'bin', 'pluribus.js')

function tempProject() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'pluribus-sync-'))
}

function writeFile(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content.trimStart(), 'utf8')
}

function runCli(cwd, args) {
  return spawnSync(process.execPath, [cliPath, ...args], {
    cwd,
    encoding: 'utf8',
  })
}

const context = `
# Identity
I am building a small API service.

# Stack
Node.js 22 and SQLite.

# Conventions
Use async/await and keep modules small.

# Goals
Make AI context portable across tools.

# Constraints
Do not add native dependencies.

# Anti-patterns
Do not duplicate project rules in tool-specific files.
`

test('sync generates Cursor .cursorrules from pluribus.md', () => {
  const dir = tempProject()
  writeFile(path.join(dir, 'pluribus.md'), context)

  const result = runCli(dir, ['sync', '--tools', 'cursor'])

  assert.equal(result.status, 0, result.stderr)
  assert.match(result.stdout, /\[cursor\].*\.cursorrules/)

  const output = fs.readFileSync(path.join(dir, '.cursorrules'), 'utf8')
  assert.match(output, /Cursor Rules — generated by Pluribus/)
  assert.match(output, /## Conventions\nUse async\/await and keep modules small\./)
  assert.match(output, /## Goals\nMake AI context portable across tools\./)
  assert.match(output, /## Constraints\nDo not add native dependencies\./)
  assert.match(output, /## Anti-patterns\nDo not duplicate project rules in tool-specific files\./)
})

test('sync generates GitHub Copilot instructions and creates .github directory', () => {
  const dir = tempProject()
  writeFile(path.join(dir, 'pluribus.md'), context)

  const result = runCli(dir, ['sync', '--tools', 'copilot'])

  assert.equal(result.status, 0, result.stderr)
  assert.match(result.stdout, /\[copilot\].*\.github\/copilot-instructions\.md/)

  const outputPath = path.join(dir, '.github', 'copilot-instructions.md')
  assert.equal(fs.existsSync(outputPath), true)

  const output = fs.readFileSync(outputPath, 'utf8')
  assert.match(output, /Generated by Pluribus/)
  assert.match(output, /## Stack\nNode\.js 22 and SQLite\./)
  assert.match(output, /## Conventions\nUse async\/await and keep modules small\./)
  assert.match(output, /## Constraints\nDo not add native dependencies\./)
})

test('sync generates Windsurf workspace rule and creates .windsurf/rules directory', () => {
  const dir = tempProject()
  writeFile(path.join(dir, 'pluribus.md'), context)

  const result = runCli(dir, ['sync', '--tools', 'windsurf'])

  assert.equal(result.status, 0, result.stderr)
  assert.match(result.stdout, /\[windsurf\].*\.windsurf\/rules\/pluribus\.md/)

  const outputPath = path.join(dir, '.windsurf', 'rules', 'pluribus.md')
  assert.equal(fs.existsSync(outputPath), true)

  const output = fs.readFileSync(outputPath, 'utf8')
  assert.match(output, /trigger: always_on/)
  assert.match(output, /Pluribus Project Rules for Windsurf Cascade/)
  assert.match(output, /## Conventions\nUse async\/await and keep modules small\./)
  assert.match(output, /## Constraints\nDo not add native dependencies\./)
  assert.match(output, /## Anti-patterns\nDo not duplicate project rules in tool-specific files\./)
})

test('sync generates Continue workspace rule and creates .continue/rules directory', () => {
  const dir = tempProject()
  writeFile(path.join(dir, 'pluribus.md'), context)

  const result = runCli(dir, ['sync', '--tools', 'continue'])

  assert.equal(result.status, 0, result.stderr)
  assert.match(result.stdout, /\[continue\].*\.continue\/rules\/pluribus\.md/)

  const outputPath = path.join(dir, '.continue', 'rules', 'pluribus.md')
  assert.equal(fs.existsSync(outputPath), true)

  const output = fs.readFileSync(outputPath, 'utf8')
  assert.match(output, /name: Pluribus Project Context/)
  assert.match(output, /alwaysApply: true/)
  assert.match(output, /Pluribus Project Context for Continue/)
  assert.match(output, /## Conventions\nUse async\/await and keep modules small\./)
  assert.match(output, /## Constraints\nDo not add native dependencies\./)
  assert.match(output, /## Anti-patterns\nDo not duplicate project rules in tool-specific files\./)
})

test('sync generates Amazon Q Developer workspace rule and creates .amazonq/rules directory', () => {
  const dir = tempProject()
  writeFile(path.join(dir, 'pluribus.md'), context)

  const result = runCli(dir, ['sync', '--tools', 'amazonq'])

  assert.equal(result.status, 0, result.stderr)
  assert.match(result.stdout, /\[amazonq\].*\.amazonq\/rules\/pluribus\.md/)

  const outputPath = path.join(dir, '.amazonq', 'rules', 'pluribus.md')
  assert.equal(fs.existsSync(outputPath), true)

  const output = fs.readFileSync(outputPath, 'utf8')
  assert.match(output, /Pluribus Project Rules for Amazon Q Developer/)
  assert.match(output, /## Conventions\nUse async\/await and keep modules small\./)
  assert.match(output, /## Constraints\nDo not add native dependencies\./)
  assert.match(output, /## Anti-patterns\nDo not duplicate project rules in tool-specific files\./)
})

test('sync writes generated files next to an explicit --source file', () => {
  const dir = tempProject()
  const projectDir = path.join(dir, 'project')
  writeFile(path.join(projectDir, 'pluribus.md'), context)

  const result = runCli(dir, ['sync', '--source', 'project/pluribus.md', '--tools', 'openclaw'])

  assert.equal(result.status, 0, result.stderr)
  assert.equal(fs.existsSync(path.join(projectDir, 'AGENTS.md')), true)
  assert.equal(fs.existsSync(path.join(dir, 'AGENTS.md')), false)

  const output = fs.readFileSync(path.join(projectDir, 'AGENTS.md'), 'utf8')
  assert.match(output, /Generated by Pluribus/)
  assert.match(output, /Source: pluribus\.md/)
})
