import test from 'node:test'
import assert from 'node:assert/strict'
import * as fs from 'node:fs'
import * as os from 'node:os'
import * as path from 'node:path'
import { fileURLToPath } from 'node:url'
import { spawn } from 'node:child_process'

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const cliPath = path.join(repoRoot, 'bin', 'pluribus.js')

function tempProject() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'pluribus-watch-'))
}

function writeFile(filePath, content) {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
  fs.writeFileSync(filePath, content.trimStart(), 'utf8')
}

function onceProcessExit(child) {
  return new Promise((resolve) => {
    child.on('exit', (code, signal) => resolve({ code, signal }))
  })
}

function waitForOutput(child, pattern) {
  let buffer = ''
  return new Promise((resolve, reject) => {
    const timeout = setTimeout(() => {
      reject(new Error(`Timed out waiting for output: ${pattern}. Got:\n${buffer}`))
    }, 5000)

    function onData(chunk) {
      buffer += chunk.toString()
      if (pattern.test(buffer)) {
        clearTimeout(timeout)
        child.stdout.off('data', onData)
        child.stderr.off('data', onData)
        resolve(buffer)
      }
    }

    child.stdout.on('data', onData)
    child.stderr.on('data', onData)
  })
}

const initialContext = `
# Identity
I am building a small API service.

# Stack
Node.js 22 and SQLite.

# Conventions
Use async/await and keep modules small.

# Goals
Make AI context portable across tools.

# Constraints
Do not add native dependencies.
`

test('watch --once syncs after pluribus.md changes and exits cleanly', async () => {
  const dir = tempProject()
  const source = path.join(dir, 'pluribus.md')
  writeFile(source, initialContext)

  const child = spawn(process.execPath, [cliPath, 'watch', '--once', '--tools', 'cursor', '--debounce', '300'], {
    cwd: dir,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'pipe'],
  })

  try {
    await waitForOutput(child, /Watching pluribus\.md/)

    fs.writeFileSync(source, initialContext.replace('Use async/await and keep modules small.', 'Updated while watch mode is running.'), 'utf8')

    const { code, signal } = await onceProcessExit(child)
    assert.equal(signal, null)
    assert.equal(code, 0)

    const outputPath = path.join(dir, '.cursorrules')
    assert.equal(fs.existsSync(outputPath), true)
    const output = fs.readFileSync(outputPath, 'utf8')
    assert.match(output, /Cursor Rules — generated by Pluribus/)
    assert.match(output, /Updated while watch mode is running\./)
  } finally {
    if (!child.killed) child.kill('SIGINT')
  }
})
