/**
 * Built-in skills for Pluribus.
 * Each skill defines: id, outputFiles[], template string, required[], optional[]
 */

export const BUILT_IN_SKILLS = {
  claude: {
    id: 'claude',
    outputFiles: ['CLAUDE.md'],
    required: ['identity', 'stack', 'conventions', 'goals', 'constraints'],
    optional: ['examples', 'anti-patterns', 'workflow', 'context'],
    template: `<!-- Generated by Pluribus {{pluribus.version}} on {{pluribus.date}} — do not edit manually -->
<!-- Source: {{pluribus.source}} -->

# Project Context for Claude

## Identity

{{identity}}

---

## Tech Stack

{{stack}}

---

## Conventions

{{conventions}}

---

## Goals

{{goals}}

---

## Constraints

> These are non-negotiable. Do not deviate from these under any circumstances.

{{constraints}}

{{#if examples}}
---

## Code Examples

{{examples}}
{{/if}}

{{#if anti-patterns}}
---

## Anti-patterns (What to Avoid)

{{anti-patterns}}
{{/if}}

{{#if workflow}}
---

## Workflow

{{workflow}}
{{/if}}

{{#if context}}
---

## Additional Context

{{context}}
{{/if}}
`,
  },

  cursor: {
    id: 'cursor',
    outputFiles: ['.cursorrules'],
    required: ['conventions', 'constraints', 'goals'],
    optional: ['identity', 'stack', 'anti-patterns'],
    template: `# Cursor Rules — generated by Pluribus {{pluribus.version}} on {{pluribus.date}}
# Source: {{pluribus.source}}
# Do not edit manually.

{{#if identity}}
## Project
{{identity}}

{{/if}}
{{#if stack}}
## Stack
{{stack}}

{{/if}}
## Conventions
{{conventions}}

## Goals
{{goals}}

## Constraints
{{constraints}}

{{#if anti-patterns}}
## Anti-patterns
{{anti-patterns}}
{{/if}}
`,
  },

  openclaw: {
    id: 'openclaw',
    outputFiles: ['AGENTS.md'],
    required: ['identity', 'stack', 'conventions', 'goals', 'constraints'],
    optional: ['examples', 'anti-patterns', 'workflow', 'context'],
    template: `<!-- Generated by Pluribus {{pluribus.version}} on {{pluribus.date}} — do not edit manually -->
<!-- Source: {{pluribus.source}} -->

# AGENTS.md

## Identity

{{identity}}

---

## Stack

{{stack}}

---

## Conventions

{{conventions}}

---

## Goals

{{goals}}

---

## Constraints

{{constraints}}

{{#if examples}}
---

## Examples

{{examples}}
{{/if}}

{{#if context}}
---

## Context

{{context}}
{{/if}}
`,
  },

  copilot: {
    id: 'copilot',
    outputFiles: ['.github/copilot-instructions.md'],
    required: ['stack', 'conventions', 'constraints'],
    optional: ['identity', 'goals', 'examples'],
    template: `<!-- Generated by Pluribus {{pluribus.version}} on {{pluribus.date}} — do not edit manually -->
<!-- Source: {{pluribus.source}} -->

{{#if identity}}
## Project
{{identity}}

{{/if}}
## Stack
{{stack}}

## Conventions
{{conventions}}

## Constraints
{{constraints}}

{{#if goals}}
## Goals
{{goals}}
{{/if}}
`,
  },

  windsurf: {
    id: 'windsurf',
    outputFiles: ['.windsurf/rules/pluribus.md'],
    required: ['conventions', 'constraints'],
    optional: ['identity', 'stack', 'goals', 'anti-patterns', 'workflow', 'context'],
    template: `---
trigger: always_on
---

<!-- Generated by Pluribus {{pluribus.version}} on {{pluribus.date}} — do not edit manually -->
<!-- Source: {{pluribus.source}} -->

# Pluribus Project Rules for Windsurf Cascade

{{#if identity}}
## Project
{{identity}}

{{/if}}
{{#if stack}}
## Stack
{{stack}}

{{/if}}
## Conventions
{{conventions}}

## Constraints
{{constraints}}

{{#if goals}}
## Goals
{{goals}}

{{/if}}
{{#if workflow}}
## Workflow
{{workflow}}

{{/if}}
{{#if anti-patterns}}
## Anti-patterns
{{anti-patterns}}

{{/if}}
{{#if context}}
## Additional Context
{{context}}
{{/if}}
`,
  },


  continue: {
    id: 'continue',
    outputFiles: ['.continue/rules/pluribus.md'],
    required: ['conventions', 'constraints'],
    optional: ['identity', 'stack', 'goals', 'anti-patterns', 'workflow', 'context'],
    template: `---
name: Pluribus Project Context
alwaysApply: true
---

<!-- Generated by Pluribus {{pluribus.version}} on {{pluribus.date}} — do not edit manually -->
<!-- Source: {{pluribus.source}} -->

# Pluribus Project Context for Continue

{{#if identity}}
## Project
{{identity}}

{{/if}}
{{#if stack}}
## Stack
{{stack}}

{{/if}}
## Conventions
{{conventions}}

## Constraints
{{constraints}}

{{#if goals}}
## Goals
{{goals}}

{{/if}}
{{#if workflow}}
## Workflow
{{workflow}}

{{/if}}
{{#if anti-patterns}}
## Anti-patterns
{{anti-patterns}}

{{/if}}
{{#if context}}
## Additional Context
{{context}}
{{/if}}
`,
  },

  zed: {
    id: 'zed',
    outputFiles: ['.rules'],
    required: ['conventions', 'constraints'],
    optional: ['identity', 'stack', 'goals', 'anti-patterns'],
    template: `# Zed AI Rules — generated by Pluribus {{pluribus.version}} on {{pluribus.date}}
# Source: {{pluribus.source}}
# Do not edit manually. Edit pluribus.md and run \`pluribus sync\`.

{{#if identity}}
## Project
{{identity}}

{{/if}}
{{#if stack}}
## Stack
{{stack}}

{{/if}}
## Conventions
{{conventions}}

## Constraints
{{constraints}}

{{#if goals}}
## Goals
{{goals}}

{{/if}}
{{#if anti-patterns}}
## Anti-patterns
{{anti-patterns}}
{{/if}}
`,
  },

  bob: {
    id: 'bob',
    outputFiles: ['.bob/rules/pluribus.md'],
    required: ['conventions', 'constraints'],
    optional: ['identity', 'stack', 'goals', 'anti-patterns', 'workflow', 'context'],
    template: `<!-- Generated by Pluribus {{pluribus.version}} on {{pluribus.date}} — do not edit manually -->
<!-- Source: {{pluribus.source}} -->

# Pluribus Project Rules for Bob

{{#if identity}}
## Project
{{identity}}

{{/if}}
{{#if stack}}
## Stack
{{stack}}

{{/if}}
## Conventions
{{conventions}}

## Constraints
{{constraints}}

{{#if goals}}
## Goals
{{goals}}

{{/if}}
{{#if workflow}}
## Workflow
{{workflow}}

{{/if}}
{{#if anti-patterns}}
## Anti-patterns
{{anti-patterns}}

{{/if}}
{{#if context}}
## Additional Context
{{context}}
{{/if}}
`,
  },

  junie: {
    id: 'junie',
    outputFiles: ['.junie/guidelines.md'],
    required: ['conventions', 'constraints'],
    optional: ['identity', 'stack', 'goals', 'anti-patterns', 'workflow', 'context'],
    template: `<!-- Generated by Pluribus {{pluribus.version}} on {{pluribus.date}} — do not edit manually -->
<!-- Source: {{pluribus.source}} -->

# Pluribus Project Guidelines for JetBrains Junie

{{#if identity}}
## Project
{{identity}}

{{/if}}
{{#if stack}}
## Stack
{{stack}}

{{/if}}
## Conventions
{{conventions}}

## Constraints
{{constraints}}

{{#if goals}}
## Goals
{{goals}}

{{/if}}
{{#if workflow}}
## Workflow
{{workflow}}

{{/if}}
{{#if anti-patterns}}
## Anti-patterns
{{anti-patterns}}

{{/if}}
{{#if context}}
## Additional Context
{{context}}
{{/if}}
`,
  },
}

export const SUPPORTED_TOOLS = Object.keys(BUILT_IN_SKILLS)
