#!/usr/bin/env node

import { execFileSync } from 'node:child_process'
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'

const repoRoot = process.cwd()
const pkg = JSON.parse(readFileSync(path.join(repoRoot, 'package.json'), 'utf8'))
const packageSpec = `${pkg.name}@latest`

function run(command, args, options = {}) {
  return execFileSync(command, args, {
    cwd: options.cwd || repoRoot,
    encoding: 'utf8',
    stdio: options.capture ? ['ignore', 'pipe', 'pipe'] : 'inherit',
    ...options,
  })
}

function assertIncludes(value, expected, label) {
  if (!value.includes(expected)) {
    throw new Error(`${label} did not include ${JSON.stringify(expected)}. Output:\n${value}`)
  }
}

function assertFileExists(filePath, label) {
  if (!existsSync(filePath)) {
    throw new Error(`${label} did not create ${filePath}`)
  }
}

const latestVersion = run('npm', ['view', pkg.name, 'version'], { capture: true }).trim()
if (!latestVersion) {
  throw new Error(`Could not resolve npm latest version for ${pkg.name}`)
}

let smokeDir

try {
  smokeDir = mkdtempSync(path.join(tmpdir(), 'pluribus-published-smoke-'))

  const versionOutput = run('npx', ['--yes', '--package', packageSpec, 'pluribus', '--version'], {
    cwd: smokeDir,
    capture: true,
  }).trim()
  if (versionOutput !== latestVersion) {
    throw new Error(`Expected published pluribus --version to be ${latestVersion}, got ${versionOutput}`)
  }

  const helpOutput = run('npx', ['--yes', '--package', packageSpec, 'pluribus', '--help'], {
    cwd: smokeDir,
    capture: true,
  })
  assertIncludes(helpOutput, `Pluribus v${latestVersion}`, 'published pluribus --help')

  run('node', ['-e', "require('fs').writeFileSync('CLAUDE.md', '# Claude context\\n'); require('fs').writeFileSync('.cursorrules', '# Cursor rules\\n')"], {
    cwd: smokeDir,
    capture: true,
  })
  const auditOutput = run('npx', ['--yes', '--package', packageSpec, 'pluribus', 'audit'], {
    cwd: smokeDir,
    capture: true,
  })
  assertIncludes(auditOutput, 'No pluribus.md found', 'published pluribus audit without source')
  assertIncludes(auditOutput, 'CLAUDE.md', 'published pluribus audit without source')
  assertIncludes(auditOutput, '.cursorrules', 'published pluribus audit without source')

  const initOutput = run(
    'npx',
    [
      '--yes',
      '--package',
      packageSpec,
      'pluribus',
      'init',
      '--name',
      'Ana',
      '--description',
      'A Node.js service',
      '--tools',
      'claude,cursor,copilot',
      '--force',
    ],
    { cwd: smokeDir, capture: true },
  )
  assertIncludes(initOutput, 'pluribus.md created', 'published pluribus init')
  assertFileExists(path.join(smokeDir, 'pluribus.md'), 'published pluribus init')

  const validateOutput = run('npx', ['--yes', '--package', packageSpec, 'pluribus', 'validate'], {
    cwd: smokeDir,
    capture: true,
  })
  assertIncludes(validateOutput, 'pluribus.md is valid', 'published pluribus validate')

  const syncDryRunOutput = run('npx', ['--yes', '--package', packageSpec, 'pluribus', 'sync', '--dry-run'], {
    cwd: smokeDir,
    capture: true,
  })
  assertIncludes(syncDryRunOutput, `Generated by Pluribus ${latestVersion}`, 'published pluribus sync --dry-run')

  console.log(`✅ published smoke passed for ${pkg.name}@${latestVersion}`)
} finally {
  if (smokeDir) rmSync(smokeDir, { recursive: true, force: true })
}
