#!/usr/bin/env node

import { execFileSync } from 'node:child_process'
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'

const repoRoot = process.cwd()
const pkg = JSON.parse(readFileSync(path.join(repoRoot, 'package.json'), 'utf8'))
const packageSpec = `${pkg.name}@latest`

function run(command, args, options = {}) {
  return execFileSync(command, args, {
    cwd: options.cwd || repoRoot,
    encoding: 'utf8',
    stdio: options.capture ? ['ignore', 'pipe', 'pipe'] : 'inherit',
    ...options,
  })
}

function assertIncludes(value, expected, label) {
  if (!value.includes(expected)) {
    throw new Error(`${label} did not include ${JSON.stringify(expected)}. Output:\n${value}`)
  }
}

function assertFileExists(filePath, label) {
  if (!existsSync(filePath)) {
    throw new Error(`${label} did not create ${filePath}`)
  }
}

function assertFileMissing(filePath, label) {
  if (existsSync(filePath)) {
    throw new Error(`${label} unexpectedly created ${filePath}`)
  }
}

function assertFails(command, args, expected, options = {}) {
  try {
    run(command, args, { ...options, capture: true })
  } catch (error) {
    const output = `${error.stdout?.toString?.() ?? ''}${error.stderr?.toString?.() ?? ''}`
    assertIncludes(output, expected, `${command} ${args.join(' ')}`)
    return output
  }
  throw new Error(`${command} ${args.join(' ')} unexpectedly succeeded`)
}

function versionAtLeast(actual, expected) {
  const actualParts = actual.split('.').map((value) => Number.parseInt(value, 10) || 0)
  const expectedParts = expected.split('.').map((value) => Number.parseInt(value, 10) || 0)
  for (let index = 0; index < Math.max(actualParts.length, expectedParts.length); index += 1) {
    const actualPart = actualParts[index] || 0
    const expectedPart = expectedParts[index] || 0
    if (actualPart > expectedPart) return true
    if (actualPart < expectedPart) return false
  }
  return true
}

const latestVersion = run('npm', ['view', pkg.name, 'version'], { capture: true }).trim()
if (!latestVersion) {
  throw new Error(`Could not resolve npm latest version for ${pkg.name}`)
}

let smokeDir

try {
  smokeDir = mkdtempSync(path.join(tmpdir(), 'pluribus-published-smoke-'))

  const versionOutput = run('npx', ['--yes', '--package', packageSpec, 'pluribus', '--version'], {
    cwd: smokeDir,
    capture: true,
  }).trim()
  if (versionOutput !== latestVersion) {
    throw new Error(`Expected published pluribus --version to be ${latestVersion}, got ${versionOutput}`)
  }

  const helpOutput = run('npx', ['--yes', '--package', packageSpec, 'pluribus', '--help'], {
    cwd: smokeDir,
    capture: true,
  })
  assertIncludes(helpOutput, `Pluribus v${latestVersion}`, 'published pluribus --help')

  if (versionAtLeast(latestVersion, '0.3.1')) {
    assertFails(
      'npx',
      ['--yes', '--package', packageSpec, 'pluribus', 'init', '--dryrun'],
      'Unknown option for `init`: --dryrun',
      { cwd: smokeDir },
    )
    assertFileMissing(path.join(smokeDir, 'pluribus.md'), 'published pluribus unknown-flag smoke')
  }

  run('node', ['-e', "require('fs').writeFileSync('CLAUDE.md', '# Claude context\\n'); require('fs').writeFileSync('.cursorrules', '# Cursor rules\\n')"], {
    cwd: smokeDir,
    capture: true,
  })
  const auditOutput = run('npx', ['--yes', '--package', packageSpec, 'pluribus', 'audit'], {
    cwd: smokeDir,
    capture: true,
  })
  assertIncludes(auditOutput, 'No pluribus.md found', 'published pluribus audit without source')
  assertIncludes(auditOutput, 'CLAUDE.md', 'published pluribus audit without source')
  assertIncludes(auditOutput, '.cursorrules', 'published pluribus audit without source')

  const initOutput = run(
    'npx',
    [
      '--yes',
      '--package',
      packageSpec,
      'pluribus',
      'init',
      '--name',
      'Ana',
      '--description',
      'A Node.js service',
      '--tools',
      'claude,cursor,copilot',
    ],
    { cwd: smokeDir, capture: true },
  )
  assertIncludes(initOutput, 'pluribus.md created', 'published pluribus init')
  assertFileExists(path.join(smokeDir, 'pluribus.md'), 'published pluribus init')

  const validateOutput = run('npx', ['--yes', '--package', packageSpec, 'pluribus', 'validate'], {
    cwd: smokeDir,
    capture: true,
  })
  assertIncludes(validateOutput, 'pluribus.md is valid', 'published pluribus validate')

  const syncDryRunOutput = run('npx', ['--yes', '--package', packageSpec, 'pluribus', 'sync', '--dry-run'], {
    cwd: smokeDir,
    capture: true,
  })
  assertIncludes(syncDryRunOutput, `Generated by Pluribus ${latestVersion}`, 'published pluribus sync --dry-run')

  console.log(`✅ published smoke passed for ${pkg.name}@${latestVersion}`)
} finally {
  if (smokeDir) rmSync(smokeDir, { recursive: true, force: true })
}
