#!/usr/bin/env node

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import { BUILT_IN_SKILLS, SUPPORTED_TOOLS } from '../src/skills/built-in.js'

const repoRoot = process.cwd()
const pkg = JSON.parse(readFileSync(path.join(repoRoot, 'package.json'), 'utf8'))
const expectedVersion = pkg.version
const auditFeedbackUrl = 'https://github.com/caioribeiroclw-pixel/pluribus/issues/new?template=audit-feedback.yml'
const supportedToolsHelp = `--tools         Comma-separated list of tools to enable (${SUPPORTED_TOOLS.join(',')})`

function run(command, args, options = {}) {
  return execFileSync(command, args, {
    cwd: options.cwd || repoRoot,
    encoding: 'utf8',
    stdio: options.capture ? ['ignore', 'pipe', 'pipe'] : 'inherit',
    ...options,
  })
}

function assertIncludes(value, expected, label) {
  if (!value.includes(expected)) {
    throw new Error(`${label} did not include ${JSON.stringify(expected)}. Output:\n${value}`)
  }
}

function assertFileExists(filePath, label) {
  if (!existsSync(filePath)) {
    throw new Error(`${label} did not create ${filePath}`)
  }
}

function assertFileMissing(filePath, label) {
  if (existsSync(filePath)) {
    throw new Error(`${label} unexpectedly created ${filePath}`)
  }
}

function assertAllSupportedToolOutputs(projectDir, label) {
  for (const tool of SUPPORTED_TOOLS) {
    const outputFiles = BUILT_IN_SKILLS[tool].outputFiles || []
    for (const outputFile of outputFiles) {
      assertFileExists(path.join(projectDir, outputFile), `${label} ${tool}`)
    }
  }
}

function assertFailsWith(command, args, expected, options = {}) {
  try {
    run(command, args, { ...options, capture: true })
  } catch (error) {
    const output = `${error.stdout || ''}${error.stderr || ''}`
    assertIncludes(output, expected, `${command} ${args.join(' ')}`)
    return output
  }

  throw new Error(`${command} ${args.join(' ')} unexpectedly succeeded`)
}

let tarball
let smokeDir

try {
  tarball = run('npm', ['pack', '--silent'], { capture: true }).trim().split(/\r?\n/).at(-1)
  if (!tarball || !tarball.endsWith('.tgz')) {
    throw new Error(`npm pack did not return a tarball name. Output: ${tarball}`)
  }

  smokeDir = mkdtempSync(path.join(tmpdir(), 'pluribus-release-smoke-'))
  const tarballPath = path.join(repoRoot, tarball)

  run('npm', ['init', '-y'], { cwd: smokeDir, stdio: 'ignore' })
  run('npm', ['install', tarballPath], { cwd: smokeDir, stdio: 'ignore' })

  const versionOutput = run('npx', ['--no-install', 'pluribus', '--version'], { cwd: smokeDir, capture: true }).trim()
  if (versionOutput !== expectedVersion) {
    throw new Error(`Expected pluribus --version to be ${expectedVersion}, got ${versionOutput}`)
  }

  const helpOutput = run('npx', ['--no-install', 'pluribus', '--help'], { cwd: smokeDir, capture: true })
  assertIncludes(helpOutput, `Pluribus v${expectedVersion}`, 'pluribus --help')
  assertIncludes(helpOutput, supportedToolsHelp, 'pluribus --help supported tools')

  assertFailsWith('npx', ['--no-install', 'pluribus', 'init', '--dryrun'], 'Unknown option for `init`: --dryrun', {
    cwd: smokeDir,
  })
  assertFileMissing(path.join(smokeDir, 'pluribus.md'), 'pluribus init --dryrun')

  const dryRunInitOutput = run('npx', ['--no-install', 'pluribus', 'init', '--dry-run'], {
    cwd: smokeDir,
    capture: true,
  })
  assertIncludes(dryRunInitOutput, 'pluribus init --dry-run preview', 'pluribus init --dry-run')
  assertIncludes(dryRunInitOutput, '<!-- pluribus:tools:', 'pluribus init --dry-run')
  assertFileMissing(path.join(smokeDir, 'pluribus.md'), 'pluribus init --dry-run')

  run('npx', ['--no-install', 'pluribus', 'init'], { cwd: smokeDir, capture: true })
  run('npx', ['--no-install', 'pluribus', 'validate'], { cwd: smokeDir, capture: true })
  const preSyncAudit = run('npx', ['--no-install', 'pluribus', 'audit'], { cwd: smokeDir, capture: true })
  assertIncludes(preSyncAudit, 'missing', 'pluribus audit before sync')
  assertIncludes(preSyncAudit, auditFeedbackUrl, 'pluribus audit before sync')
  const syncOutput = run('npx', ['--no-install', 'pluribus', 'sync', '--dry-run'], { cwd: smokeDir, capture: true })
  assertIncludes(syncOutput, `Generated by Pluribus ${expectedVersion}`, 'pluribus sync --dry-run')

  run('npx', ['--no-install', 'pluribus', 'sync'], { cwd: smokeDir, capture: true })
  const postSyncAudit = run('npx', ['--no-install', 'pluribus', 'audit', '--strict'], { cwd: smokeDir, capture: true })
  assertIncludes(postSyncAudit, 'Generated context files are in sync', 'pluribus audit after sync')

  const auditJsonPath = path.join(smokeDir, 'audit.json')
  const auditCiStdout = run(
    'npx',
    ['--no-install', 'pluribus', 'audit', '--ci', '--json', '--output', auditJsonPath],
    { cwd: smokeDir, capture: true },
  )
  if (auditCiStdout.trim() !== '') {
    throw new Error(`pluribus audit --ci --json --output should keep stdout quiet. Output:\n${auditCiStdout}`)
  }
  const auditJson = JSON.parse(readFileSync(auditJsonPath, 'utf8'))
  if (!auditJson.ok || auditJson.summary.current !== 3 || auditJson.summary.drifted !== 0) {
    throw new Error(`Unexpected audit JSON result:\n${JSON.stringify(auditJson, null, 2)}`)
  }
  if (auditJson.feedback !== auditFeedbackUrl) {
    throw new Error(`Expected audit JSON feedback to be ${auditFeedbackUrl}, got ${auditJson.feedback}`)
  }

  const generatedClaude = readFileSync(path.join(smokeDir, 'CLAUDE.md'), 'utf8')
  assertIncludes(generatedClaude, `Generated by Pluribus ${expectedVersion}`, 'generated CLAUDE.md')

  const globalPrefix = path.join(smokeDir, 'global-prefix')
  run('npm', ['install', '--global', '--prefix', globalPrefix, tarballPath], { stdio: 'ignore' })
  const globalBin = process.platform === 'win32'
    ? path.join(globalPrefix, 'pluribus.cmd')
    : path.join(globalPrefix, 'bin', 'pluribus')
  assertFileExists(globalBin, 'npm install -g pluribus-context')
  const globalVersionOutput = run(globalBin, ['--version'], { capture: true }).trim()
  if (globalVersionOutput !== expectedVersion) {
    throw new Error(`Expected global pluribus --version to be ${expectedVersion}, got ${globalVersionOutput}`)
  }
  run('npm', ['uninstall', '--global', '--prefix', globalPrefix, pkg.name], { stdio: 'ignore' })
  assertFileMissing(globalBin, 'npm uninstall -g pluribus-context')

  const allToolsDir = path.join(smokeDir, 'all-supported-tools')
  mkdirSync(allToolsDir)
  run(
    'npx',
    [
      '--no-install',
      'pluribus',
      'init',
      '--name',
      'Ana',
      '--description',
      'A Node.js service',
      '--tools',
      SUPPORTED_TOOLS.join(','),
    ],
    { cwd: allToolsDir, capture: true },
  )
  const allToolsSync = run('npx', ['--no-install', 'pluribus', 'sync'], { cwd: allToolsDir, capture: true })
  for (const tool of SUPPORTED_TOOLS) {
    assertIncludes(allToolsSync, `[${tool}]`, 'pluribus sync all supported tools')
  }
  assertAllSupportedToolOutputs(allToolsDir, 'pluribus sync all supported tools')

  console.log(`✅ release smoke passed for ${pkg.name}@${expectedVersion}`)
} finally {
  if (smokeDir) rmSync(smokeDir, { recursive: true, force: true })
  if (tarball) rmSync(path.join(repoRoot, tarball), { force: true })
}
