#!/usr/bin/env node

import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'

const repoRoot = process.cwd()
const pkg = JSON.parse(readFileSync(path.join(repoRoot, 'package.json'), 'utf8'))
const expectedVersion = pkg.version

function run(command, args, options = {}) {
  return execFileSync(command, args, {
    cwd: options.cwd || repoRoot,
    encoding: 'utf8',
    stdio: options.capture ? ['ignore', 'pipe', 'pipe'] : 'inherit',
    ...options,
  })
}

function assertIncludes(value, expected, label) {
  if (!value.includes(expected)) {
    throw new Error(`${label} did not include ${JSON.stringify(expected)}. Output:\n${value}`)
  }
}

let tarball
let smokeDir

try {
  tarball = run('npm', ['pack', '--silent'], { capture: true }).trim().split(/\r?\n/).at(-1)
  if (!tarball || !tarball.endsWith('.tgz')) {
    throw new Error(`npm pack did not return a tarball name. Output: ${tarball}`)
  }

  smokeDir = mkdtempSync(path.join(tmpdir(), 'pluribus-release-smoke-'))
  const tarballPath = path.join(repoRoot, tarball)

  run('npm', ['init', '-y'], { cwd: smokeDir, stdio: 'ignore' })
  run('npm', ['install', tarballPath], { cwd: smokeDir, stdio: 'ignore' })

  const versionOutput = run('npx', ['--no-install', 'pluribus', '--version'], { cwd: smokeDir, capture: true }).trim()
  if (versionOutput !== expectedVersion) {
    throw new Error(`Expected pluribus --version to be ${expectedVersion}, got ${versionOutput}`)
  }

  const helpOutput = run('npx', ['--no-install', 'pluribus', '--help'], { cwd: smokeDir, capture: true })
  assertIncludes(helpOutput, `Pluribus v${expectedVersion}`, 'pluribus --help')

  run('npx', ['--no-install', 'pluribus', 'init', '--force'], { cwd: smokeDir, capture: true })
  run('npx', ['--no-install', 'pluribus', 'validate'], { cwd: smokeDir, capture: true })
  const preSyncAudit = run('npx', ['--no-install', 'pluribus', 'audit'], { cwd: smokeDir, capture: true })
  assertIncludes(preSyncAudit, 'missing', 'pluribus audit before sync')
  const syncOutput = run('npx', ['--no-install', 'pluribus', 'sync', '--dry-run'], { cwd: smokeDir, capture: true })
  assertIncludes(syncOutput, `Generated by Pluribus ${expectedVersion}`, 'pluribus sync --dry-run')

  run('npx', ['--no-install', 'pluribus', 'sync'], { cwd: smokeDir, capture: true })
  const postSyncAudit = run('npx', ['--no-install', 'pluribus', 'audit', '--strict'], { cwd: smokeDir, capture: true })
  assertIncludes(postSyncAudit, 'Generated context files are in sync', 'pluribus audit after sync')
  const generatedClaude = readFileSync(path.join(smokeDir, 'CLAUDE.md'), 'utf8')
  assertIncludes(generatedClaude, `Generated by Pluribus ${expectedVersion}`, 'generated CLAUDE.md')

  console.log(`✅ release smoke passed for ${pkg.name}@${expectedVersion}`)
} finally {
  if (smokeDir) rmSync(smokeDir, { recursive: true, force: true })
  if (tarball) rmSync(path.join(repoRoot, tarball), { force: true })
}
