#!/usr/bin/env node

import { execFileSync } from 'node:child_process'
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'

const repoRoot = process.cwd()
const pkg = JSON.parse(readFileSync(path.join(repoRoot, 'package.json'), 'utf8'))
const packetPath = path.join(repoRoot, 'docs/community-review-packet.md')
const packageSpec = `${pkg.name}@latest`
const reviewCommands = [
  'mkdir pluribus-review && cd pluribus-review',
  `npx --yes ${packageSpec} --version`,
  `npx --yes ${packageSpec} init --dry-run --name "Review" --description "Disposable review project" --tools claude,cursor,copilot`,
  `npx --yes ${packageSpec} init --name "Review" --description "Disposable review project" --tools claude,cursor,copilot`,
  `npx --yes ${packageSpec} validate`,
  `npx --yes ${packageSpec} sync --dry-run`,
  `npx --yes ${packageSpec} audit --ci --json --output pluribus-audit.json || test $? -eq 1`,
]

function run(command, args, options = {}) {
  return execFileSync(command, args, {
    cwd: options.cwd || repoRoot,
    encoding: 'utf8',
    stdio: options.capture ? ['ignore', 'pipe', 'pipe'] : 'inherit',
    ...options,
  })
}

function runAllowFailure(command, args, options = {}) {
  try {
    const stdout = run(command, args, { ...options, capture: true })
    return { status: 0, stdout, stderr: '' }
  } catch (error) {
    return {
      status: error.status ?? 1,
      stdout: error.stdout?.toString?.() ?? '',
      stderr: error.stderr?.toString?.() ?? '',
    }
  }
}

function assertIncludes(value, expected, label) {
  if (!value.includes(expected)) {
    throw new Error(`${label} did not include ${JSON.stringify(expected)}. Output:\n${value}`)
  }
}

function assertFileExists(filePath, label) {
  if (!existsSync(filePath)) {
    throw new Error(`${label} did not create ${filePath}`)
  }
}

function assertFileMissing(filePath, label) {
  if (existsSync(filePath)) {
    throw new Error(`${label} unexpectedly created ${filePath}`)
  }
}

function assertPacketDocumentsSmoke() {
  const packet = readFileSync(packetPath, 'utf8')
  assertIncludes(packet, '## 60-second review smoke', 'community review packet')
  for (const command of reviewCommands) {
    assertIncludes(packet, command, 'community review packet smoke command')
  }
}

assertPacketDocumentsSmoke()

const latestVersion = run('npm', ['view', pkg.name, 'version'], { capture: true }).trim()
if (!latestVersion) {
  throw new Error(`Could not resolve npm latest version for ${pkg.name}`)
}

let smokeDir

try {
  smokeDir = mkdtempSync(path.join(tmpdir(), 'pluribus-review-smoke-'))
  const reviewDir = path.join(smokeDir, 'pluribus-review')
  mkdirSync(reviewDir)

  const versionOutput = run('npx', ['--yes', packageSpec, '--version'], { cwd: reviewDir, capture: true }).trim()
  if (versionOutput !== latestVersion) {
    throw new Error(`Expected review smoke --version to be ${latestVersion}, got ${versionOutput}`)
  }

  const initPreview = run(
    'npx',
    [
      '--yes',
      packageSpec,
      'init',
      '--dry-run',
      '--name',
      'Review',
      '--description',
      'Disposable review project',
      '--tools',
      'claude,cursor,copilot',
    ],
    { cwd: reviewDir, capture: true },
  )
  assertIncludes(initPreview, 'Preview only — no files were written', 'review smoke init --dry-run')
  assertFileMissing(path.join(reviewDir, 'pluribus.md'), 'review smoke init --dry-run')

  const initOutput = run(
    'npx',
    [
      '--yes',
      packageSpec,
      'init',
      '--name',
      'Review',
      '--description',
      'Disposable review project',
      '--tools',
      'claude,cursor,copilot',
    ],
    { cwd: reviewDir, capture: true },
  )
  assertIncludes(initOutput, 'pluribus.md created', 'review smoke init')
  assertFileExists(path.join(reviewDir, 'pluribus.md'), 'review smoke init')

  const validateOutput = run('npx', ['--yes', packageSpec, 'validate'], { cwd: reviewDir, capture: true })
  assertIncludes(validateOutput, 'pluribus.md is valid', 'review smoke validate')

  const syncPreview = run('npx', ['--yes', packageSpec, 'sync', '--dry-run'], { cwd: reviewDir, capture: true })
  assertIncludes(syncPreview, `Generated by Pluribus ${latestVersion}`, 'review smoke sync --dry-run')
  assertFileMissing(path.join(reviewDir, 'CLAUDE.md'), 'review smoke sync --dry-run')
  assertFileMissing(path.join(reviewDir, '.cursorrules'), 'review smoke sync --dry-run')
  assertFileMissing(path.join(reviewDir, '.github/copilot-instructions.md'), 'review smoke sync --dry-run')

  const audit = runAllowFailure(
    'npx',
    ['--yes', packageSpec, 'audit', '--ci', '--json', '--output', 'pluribus-audit.json'],
    { cwd: reviewDir },
  )
  if (audit.status !== 1) {
    throw new Error(`Expected review smoke audit to exit 1 before generated files are synced, got ${audit.status}`)
  }
  if (audit.stdout.trim()) {
    throw new Error(`Expected review smoke audit --output to keep stdout empty. Output:\n${audit.stdout}`)
  }
  assertIncludes(audit.stderr, '::error file=CLAUDE.md', 'review smoke audit annotations')
  assertIncludes(audit.stderr, '::error file=.cursorrules', 'review smoke audit annotations')
  assertIncludes(audit.stderr, '::error file=.github/copilot-instructions.md', 'review smoke audit annotations')

  const auditJsonPath = path.join(reviewDir, 'pluribus-audit.json')
  assertFileExists(auditJsonPath, 'review smoke audit --output')
  const auditJson = JSON.parse(readFileSync(auditJsonPath, 'utf8'))
  if (auditJson.ok !== false || auditJson.summary?.missing !== 3 || auditJson.results?.length !== 3) {
    throw new Error(`Unexpected review smoke audit JSON:\n${JSON.stringify(auditJson, null, 2)}`)
  }
  assertIncludes(auditJson.feedback || '', 'issues/new?template=audit-feedback.yml', 'review smoke audit feedback URL')

  console.log(`✅ community review packet smoke passed for ${pkg.name}@latest (${latestVersion})`)
} finally {
  if (smokeDir) {
    rmSync(smokeDir, { recursive: true, force: true })
  }
}
